version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: talkinbird
      POSTGRES_PASSWORD: "5pOWcvhAyYlwthKbLU39KeDqo19btga_"
    volumes:
      - talkinbird_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "vmRvgF8Hdb70ZBb2GlK6nCudfWj3Xj4L"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  talkinbird_data:
